// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cov_cpp
arma::mat cov_cpp(const arma::mat& X);
RcppExport SEXP _rnp_cov_cpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(cov_cpp(X));
    return rcpp_result_gen;
END_RCPP
}
// cor_cpp
arma::mat cor_cpp(const arma::mat& X, int metodo);
RcppExport SEXP _rnp_cor_cpp(SEXP XSEXP, SEXP metodoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type metodo(metodoSEXP);
    rcpp_result_gen = Rcpp::wrap(cor_cpp(X, metodo));
    return rcpp_result_gen;
END_RCPP
}
// dist_pairwise_cpp
arma::mat dist_pairwise_cpp(const arma::mat& X, int metodo, double p, const arma::mat& inv_cov);
RcppExport SEXP _rnp_dist_pairwise_cpp(SEXP XSEXP, SEXP metodoSEXP, SEXP pSEXP, SEXP inv_covSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type metodo(metodoSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type inv_cov(inv_covSEXP);
    rcpp_result_gen = Rcpp::wrap(dist_pairwise_cpp(X, metodo, p, inv_cov));
    return rcpp_result_gen;
END_RCPP
}
// ecdf_cpp
arma::vec ecdf_cpp(const arma::vec& x, const arma::vec& pontos);
RcppExport SEXP _rnp_ecdf_cpp(SEXP xSEXP, SEXP pontosSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type pontos(pontosSEXP);
    rcpp_result_gen = Rcpp::wrap(ecdf_cpp(x, pontos));
    return rcpp_result_gen;
END_RCPP
}
// ranks_cpp
arma::vec ranks_cpp(const arma::vec& x);
RcppExport SEXP _rnp_ranks_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(ranks_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// binning_cpp
arma::uvec binning_cpp(const arma::vec& x, const arma::vec& breaks);
RcppExport SEXP _rnp_binning_cpp(SEXP xSEXP, SEXP breaksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type breaks(breaksSEXP);
    rcpp_result_gen = Rcpp::wrap(binning_cpp(x, breaks));
    return rcpp_result_gen;
END_RCPP
}
// markov_npassos_cpp
arma::mat markov_npassos_cpp(const arma::mat& P, int n);
RcppExport SEXP _rnp_markov_npassos_cpp(SEXP PSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type P(PSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(markov_npassos_cpp(P, n));
    return rcpp_result_gen;
END_RCPP
}
// markov_estacionaria_cpp
arma::vec markov_estacionaria_cpp(const arma::mat& P);
RcppExport SEXP _rnp_markov_estacionaria_cpp(SEXP PSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type P(PSEXP);
    rcpp_result_gen = Rcpp::wrap(markov_estacionaria_cpp(P));
    return rcpp_result_gen;
END_RCPP
}
// momentos_cpp
Rcpp::List momentos_cpp(const arma::vec& x, int ordem);
RcppExport SEXP _rnp_momentos_cpp(SEXP xSEXP, SEXP ordemSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type ordem(ordemSEXP);
    rcpp_result_gen = Rcpp::wrap(momentos_cpp(x, ordem));
    return rcpp_result_gen;
END_RCPP
}
// ols_fit_cpp
Rcpp::List ols_fit_cpp(const arma::mat& X, const arma::vec& y);
RcppExport SEXP _rnp_ols_fit_cpp(SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(ols_fit_cpp(X, y));
    return rcpp_result_gen;
END_RCPP
}
// bootstrap_stat_cpp
arma::vec bootstrap_stat_cpp(const arma::vec& x, int B, int stat_id);
RcppExport SEXP _rnp_bootstrap_stat_cpp(SEXP xSEXP, SEXP BSEXP, SEXP stat_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type stat_id(stat_idSEXP);
    rcpp_result_gen = Rcpp::wrap(bootstrap_stat_cpp(x, B, stat_id));
    return rcpp_result_gen;
END_RCPP
}
// jackknife_stat_cpp
arma::vec jackknife_stat_cpp(const arma::vec& x, int stat_id);
RcppExport SEXP _rnp_jackknife_stat_cpp(SEXP xSEXP, SEXP stat_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type stat_id(stat_idSEXP);
    rcpp_result_gen = Rcpp::wrap(jackknife_stat_cpp(x, stat_id));
    return rcpp_result_gen;
END_RCPP
}
// permutacao_difmedias_cpp
arma::vec permutacao_difmedias_cpp(const arma::vec& x, const arma::vec& y, int B);
RcppExport SEXP _rnp_permutacao_difmedias_cpp(SEXP xSEXP, SEXP ySEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(permutacao_difmedias_cpp(x, y, B));
    return rcpp_result_gen;
END_RCPP
}
// ridge_cpp
arma::vec ridge_cpp(const arma::mat& X, const arma::vec& y, double lambda);
RcppExport SEXP _rnp_ridge_cpp(SEXP XSEXP, SEXP ySEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(ridge_cpp(X, y, lambda));
    return rcpp_result_gen;
END_RCPP
}
// enet_cd_cpp
arma::vec enet_cd_cpp(const arma::mat& X, const arma::vec& y, double lambda, double alpha, int max_iter, double tol);
RcppExport SEXP _rnp_enet_cd_cpp(SEXP XSEXP, SEXP ySEXP, SEXP lambdaSEXP, SEXP alphaSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(enet_cd_cpp(X, y, lambda, alpha, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// irls_cpp
Rcpp::List irls_cpp(const arma::mat& X, const arma::vec& y, int psi_tipo, double c_tuning, int max_iter, double tol);
RcppExport SEXP _rnp_irls_cpp(SEXP XSEXP, SEXP ySEXP, SEXP psi_tipoSEXP, SEXP c_tuningSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type psi_tipo(psi_tipoSEXP);
    Rcpp::traits::input_parameter< double >::type c_tuning(c_tuningSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(irls_cpp(X, y, psi_tipo, c_tuning, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rnp_cov_cpp", (DL_FUNC) &_rnp_cov_cpp, 1},
    {"_rnp_cor_cpp", (DL_FUNC) &_rnp_cor_cpp, 2},
    {"_rnp_dist_pairwise_cpp", (DL_FUNC) &_rnp_dist_pairwise_cpp, 4},
    {"_rnp_ecdf_cpp", (DL_FUNC) &_rnp_ecdf_cpp, 2},
    {"_rnp_ranks_cpp", (DL_FUNC) &_rnp_ranks_cpp, 1},
    {"_rnp_binning_cpp", (DL_FUNC) &_rnp_binning_cpp, 2},
    {"_rnp_markov_npassos_cpp", (DL_FUNC) &_rnp_markov_npassos_cpp, 2},
    {"_rnp_markov_estacionaria_cpp", (DL_FUNC) &_rnp_markov_estacionaria_cpp, 1},
    {"_rnp_momentos_cpp", (DL_FUNC) &_rnp_momentos_cpp, 2},
    {"_rnp_ols_fit_cpp", (DL_FUNC) &_rnp_ols_fit_cpp, 2},
    {"_rnp_bootstrap_stat_cpp", (DL_FUNC) &_rnp_bootstrap_stat_cpp, 3},
    {"_rnp_jackknife_stat_cpp", (DL_FUNC) &_rnp_jackknife_stat_cpp, 2},
    {"_rnp_permutacao_difmedias_cpp", (DL_FUNC) &_rnp_permutacao_difmedias_cpp, 3},
    {"_rnp_ridge_cpp", (DL_FUNC) &_rnp_ridge_cpp, 3},
    {"_rnp_enet_cd_cpp", (DL_FUNC) &_rnp_enet_cd_cpp, 6},
    {"_rnp_irls_cpp", (DL_FUNC) &_rnp_irls_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_rnp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
