# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cov_cpp <- function(X) {
    .Call(`_rnp_cov_cpp`, X)
}

cor_cpp <- function(X, metodo) {
    .Call(`_rnp_cor_cpp`, X, metodo)
}

dist_pairwise_cpp <- function(X, metodo, p, inv_cov) {
    .Call(`_rnp_dist_pairwise_cpp`, X, metodo, p, inv_cov)
}

ecdf_cpp <- function(x, pontos) {
    .Call(`_rnp_ecdf_cpp`, x, pontos)
}

ranks_cpp <- function(x) {
    .Call(`_rnp_ranks_cpp`, x)
}

binning_cpp <- function(x, breaks) {
    .Call(`_rnp_binning_cpp`, x, breaks)
}

markov_npassos_cpp <- function(P, n) {
    .Call(`_rnp_markov_npassos_cpp`, P, n)
}

markov_estacionaria_cpp <- function(P) {
    .Call(`_rnp_markov_estacionaria_cpp`, P)
}

momentos_cpp <- function(x, ordem) {
    .Call(`_rnp_momentos_cpp`, x, ordem)
}

ols_fit_cpp <- function(X, y) {
    .Call(`_rnp_ols_fit_cpp`, X, y)
}

bootstrap_stat_cpp <- function(x, B, stat_id) {
    .Call(`_rnp_bootstrap_stat_cpp`, x, B, stat_id)
}

jackknife_stat_cpp <- function(x, stat_id) {
    .Call(`_rnp_jackknife_stat_cpp`, x, stat_id)
}

permutacao_difmedias_cpp <- function(x, y, B) {
    .Call(`_rnp_permutacao_difmedias_cpp`, x, y, B)
}

ridge_cpp <- function(X, y, lambda) {
    .Call(`_rnp_ridge_cpp`, X, y, lambda)
}

enet_cd_cpp <- function(X, y, lambda, alpha, max_iter, tol) {
    .Call(`_rnp_enet_cd_cpp`, X, y, lambda, alpha, max_iter, tol)
}

irls_cpp <- function(X, y, psi_tipo, c_tuning, max_iter, tol) {
    .Call(`_rnp_irls_cpp`, X, y, psi_tipo, c_tuning, max_iter, tol)
}

